name: Format

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: npm install
        run: |
          npm install
      - name: format code
        run: |
          npm run format
      - name: push formatted code
        run: |
          git config --global user.name "abhishzk" github-actions
          git config --global user.email "abhishzk.dev@gmail.com" github-actions@github.com
          git add --all
          git diff-index --quiet HEAD || git commit -m "Format Code"
          git pull
          git push
